### ISSUE TITLE
GW2000 sends plain text

### ISSUE THREAD

**Issue by johlym** [djjudas21/ecowitt-exporter#16]
Stumbled across this repo in my efforts to try to get my weather data into Prometheus. Based on the GW1101 being on the list in the README, I assumed the GW2000 would work, too. It doesn't seem to. It looks like the GW2000 is sending a plaintext body. Here's a representation using the `dummyhttp` server to print the incoming POST request:

```
~# dummyhttp -p 8188 -vv
dummyhttp v1.0.3 listening on http://0.0.0.0:8188
2024-43-06 17:43:50 10.31.102.114:59872 POST /report HTTP/1.1
┌─Incoming request
│ POST /report HTTP/1.1
│ Connection: Close
│ Content-Length: 472
│ Content-Type: application/x-www-form-urlencoded
│ Host: 10.31.102.88
│ Body:
│ PASSKEY=50E4A2B2A92ED2BB4CEFD4478A6312F9&stationtype=GW2000B_V2.1.8&runtime=1755701&dateutc=2024-01-07+01:43:50&tempinf=68.90&humidityin=42&baromrelin=29.244&baromabsin=29.323&tempf=39.74&humidity=99&winddir=60&windspeedmph=1.34&windgustmph=2.24&maxdailygust=12.53&solarradiation=0.00&uv=0&rainratein=0.000&eventrainin=1.689&hourlyrainin=0.000&dailyrainin=0.567&weeklyrainin=1.709&monthlyrainin=1.697&yearlyrainin=1.697&totalrainin=1.697&wh65batt=0&freq=915M&model=GW2000B
┌─Outgoing response
│ HTTP/1.1 200 OK
│ Content-Length: 9
│ Content-Type: text/plain; charset=utf-8
│ Date: Sat, 6 Jan 2024 17:43:50 -0800
│ Body:
│ dummyhttp
```

Am I missing something here?

**Comment by djjudas21** [comment]
Off the top of my head, that looks OK. I don't have the GW1101 either though. What behaviour are you seeing from the exporter in debug mode?

**Comment by johlym** [comment]
Hmm. Now I can't replicate it. Initially, I was seeing:

```
DEBUG in ecowitt_exporter: Body: b''
```

...so I thought that perhaps the expected and actual request bodies were different, but now I'm getting a complete, clean input:

```
[2024-01-08 10:39:32,577] DEBUG in ecowitt_exporter: Body: b'PASSKEY=50E4A2B2A92ED2BB4CEFD4478A6312F9&stationtype=GW2000B_V3.0.9...
[2024-01-08 10:39:32,578] DEBUG in ecowitt_exporter: Received raw value PASSKEY: 50E4A2B2A92ED2BB4CEFD4478A6312F9
[2024-01-08 10:39:32,578] DEBUG in ecowitt_exporter: Received raw value stationtype: GW2000B_V3.0.9
...
```

**Comment by djjudas21** [comment]
Is this working properly for you now?

**Comment by johlym** [comment]
Apologies. Yes, working great, now. 👍🏻On Jan 9, 2024, at 1:49 AM, Jonathan ***@***.***> wrote:﻿
Is this working properly for you now?
